name: Release pipeline
env:
  RELEASE_PIPELINE_VERSION: 1.2.4
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment name, or "all"
        required: true
        default: dev
        type: string
      force-redeploy:
        description: Deploy to all environments, even if the version hasn't changed.
        required: false
        default: false
        type: boolean
      rebuild:
        description: Rebuild all artifacts, even if they already exist.
        required: false
        default: false
        type: boolean
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
jobs:
  release:
    uses: >-
      cds-snc/canadalogin-release-pipeline/.github/workflows/release-pipeline.yml@v${{
      env.RELEASE_PIPELINE_VERSION }}
    with:
      environment: ${{ inputs.environment || '' }}
      force-redeploy: ${{ inputs.force-redeploy || false }}
      rebuild: ${{ inputs.rebuild || false }}
    secrets: inherit
