schema_version: 2
application: migration-application
profile: spa-ecs

environments: [dev, test, staging, prod]

frontend:
  environment:
    VITE_BACKEND_API_URL:
      var: VITE_BACKEND_API_URL
    VITE_GOOGLE_ANALYTICS_ID:
      var: VITE_GOOGLE_ANALYTICS_ID
  invalidation_paths: [/index.html]

backend:
  dockerfile: backend/Dockerfile

load_tests:
  enabled: true